# -*- coding: utf-8 -*-
"""Prueba v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCKY4p0ql8IOULNpmIyxJHnm861x5OTA
"""

# Libreria para descargar el audio de los videos de Youtube
# pip install pytube
# Modelo de ASR
# pip install -U openai-whisper

# pip install streamlit
# pip install transformers

import pytube
import whisper
import streamlit as st
from transformers import pipeline

videoURL = st.text_input("Enter video link", "")
youtubeVideo = pytube.YouTube(videoURL)

audio = youtubeVideo.streams.get_audio_only()
audio.download(filename='tmp.mp4')
model = whisper.load_model('small')

result = model.transcribe('tmp.mp4')

print(result['text'])

st.header("Video Summarizer 🎬")


if st.button("Get Summary"):

    summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")
    x3 = summarizer(result['text'][:4000], max_length=230)

    res = x3[0]["summary_text"]

    st.write(res)